language: ruby
rvm:
  - "1.9.3"
env:
  - DB=mysql
# uncomment this line if your project needs to run something other than `rake`:
script: rake db:drop && rake db:setup && rake db:migrate:status && rspec -c
before_script:
  - cp config/database.yml.example config/database.yml